---
name: PocketRPG
author: Sandertv
main: PocketRPG\Main
version: 0.3.0
api: [2.0.0, 1.13.0]
load: POSTWORLD

commands:
  quest:
    description: Quest help command
    usage: /quest help
    aliases: [q]
  rpg:
    description: Main RPG command
    usage: /rpg start mage|warrior|assassin|tank
  party:
    description: Main party command
    usage: /party help 1
  
permissions:
  rpg.break:
    default: op
    description: allow breaking in RPG world
  rpg.place:
    default: op
    description: allow placing in RPG world
...
